version: '3.4'

services:
  db:
    container_name: sql_server2022
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Oranges1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

  db2:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  repositorypattern:
    image: ${DOCKER_REGISTRY-}repositorypattern
    build:
      context: .
      dockerfile: Repository Pattern/Dockerfile
    depends_on:
     - "db2"
